package view;

import common.ConnectDatabase;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class AddStuInClass extends javax.swing.JPanel {
    private JFrame parentFrame;
    Connection connection = null;
//    PreparedStatement pst = null;
//    ResultSet rs = null;
    String id = null;
    String created_at,project_name,start_date,end_date,updated_at,homeroom_teacher,user_id,user_name;
    
    
    /**
     * Creates new form AddStuInClass
     */
    public AddStuInClass(String id1) {
        initComponents();
        id = id1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addStuInClass = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Thêm học sinh vào lớp học ");

        jLabel2.setText("Nhập id học sinh");

        addStuInClass.setText("THÊM");
        addStuInClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStuInClassMouseClicked(evt);
            }
        });
        addStuInClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStuInClassActionPerformed(evt);
            }
        });

        jButton2.setText("HỦY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(addStuInClass))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStuInClass)
                    .addComponent(jButton2))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDActionPerformed

    private void addStuInClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStuInClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStuInClassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addStuInClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStuInClassMouseClicked
    
        connection = ConnectDatabase.getMyConnection();
        
        try {
            String urlTest1= "SELECT * FROM `tbl_account` WHERE id = ? AND role = 3";
            PreparedStatement psTest1= connection.prepareStatement(urlTest1);
            psTest1.setString(1, textID.getText());
            ResultSet rsTest1 = psTest1.executeQuery();

            boolean foundResult1 = false; // Biến kiểm tra kết quả đã được tìm thấy hay chưa

            while (rsTest1.next()) {
                user_name = rsTest1.getString("username");
                foundResult1 = true; // Đánh dấu kết quả đã được tìm thấy
            }

            if (!foundResult1) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            else{
                String urlTest= "SELECT * FROM `tbl_member` WHERE project_id = ? AND user_id = ?";
                PreparedStatement psTest;
                psTest = connection.prepareStatement(urlTest);
                psTest.setString(1, id);
                psTest.setString(2, textID.getText());
                ResultSet rsTest = psTest.executeQuery();

                boolean foundResult = false; // Biến kiểm tra kết quả đã được tìm thấy hay chưa

                while (rsTest.next()) {
                    foundResult = true; // Đánh dấu kết quả đã được tìm thấy
                }

                if (foundResult) {
                    JOptionPane.showMessageDialog(this, "Học sinh đã được thêm vào lớp học", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    try {
                        String url1 = "SELECT `created_at`, `created_by`, `end_date`, `name`, `start_date`, `updated_at` FROM `tbl_classes` WHERE id = ?";
                        PreparedStatement ps1 = connection.prepareStatement(url1);
                        ps1.setString(1, id);
                        ResultSet rs1 = ps1.executeQuery();
                        System.out.println("------");
                        while (rs1.next()) {
                            created_at = rs1.getString("created_at");
                            homeroom_teacher = rs1.getString("created_by");
                            project_name = rs1.getString("name");
                            start_date = rs1.getString("start_date");
                            end_date = rs1.getString("end_date");
                            updated_at = rs1.getString("updated_at");
                        }
                        System.out.println(created_at);
                        System.out.println(homeroom_teacher);
                        System.out.println(project_name);
                        System.out.println(start_date);
                        System.out.println(end_date);
                        System.out.println(updated_at);
                        String code = homeroom_teacher +"-"+id;

                        String url2 = "INSERT INTO `tbl_member`(`code`, `created_at`, `end_date`, `homeroom_teacher`, "
                                + "`note`, `project_id`, `project_name`, `start_date`, `updated_at`, `user_id`, `user_name`) "
                                + "VALUES (?,?,?,?,?,?,?,?,?,?,?)";

                        PreparedStatement ps2 = connection.prepareStatement(url2);
                        ps2.setString(1, code);
                        ps2.setString(2, created_at);
                        ps2.setString(3, end_date);
                        ps2.setString(4, homeroom_teacher);
                        ps2.setString(5, null);
                        ps2.setString(6, id);
                        ps2.setString(7, project_name);
                        ps2.setString(8, start_date);
                        ps2.setString(9, updated_at);
                        ps2.setString(10, textID.getText());
                        ps2.setString(11, user_name);
                        ps2.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Thêm học sinh vào lớp học thành công!");
                        Window window = SwingUtilities.getWindowAncestor(this);
                            if (window != null) {
                                window.dispose();
                            }
                    } catch (Exception e) {
                        System.out.println(e);
                        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra " + e);
                    }
                }
            } 
        } catch (SQLException ex) {
            Logger.getLogger(AddStuInClass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addStuInClassMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStuInClass;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textID;
    // End of variables declaration//GEN-END:variables
}
